### ISSUE TITLE
Support custom Visual Studio installation

### ISSUE THREAD

**Issue by deevus** [remcoros/DuplicateExtensionFinder#1]
My Visual Studio is at `C:\IDEs\...` so I get an exception when running the project. I was able to fix it by editing the path, but I think a more general solution is warranted.

**Comment by remcoros** [comment]
Do you have a good suggestion? Right now, it uses "program files" as a prefix.

Should the full path to the "extensions" dir be an argument? Or just the path to the visual studio installation (base) path?

**Comment by deevus** [comment]
Do the extensions always reside within the Visual Studio installation path? If so, I would probably use that. Default it to what you have now.

**Comment by remcoros** [comment]
Ok, I did it. A little bit different though. It still takes those two vs14 paths by default, but now you can override this by specifying one or multiple paths on the command-line. It has to be the full path to the extension dir(s) though. I updated the readme.

I saw that vs 2017 install locations changed a bit, so if vs2017 still has this issue, you could use this tool too I suppose (untested).

Oh note that you'll have to specify the appdata dir yourself too when doing this. So creating a .bat or anything could be useful in this case.

**Comment by remcoros** [comment]
Oh note that you'll have to specify the appdata dir yourself too when doing this. So creating a .bat or anything could be useful in this case.

**Comment by deevus** [comment]
Thanks
