### ISSUE TITLE
Add release binaries

### ISSUE THREAD

**Issue by deevus** [remcoros/DuplicateExtensionFinder#2]
Would be great if there were some release binaries to save having to checkout the project and build it yourself.

**Comment by MrChriZ** [comment]
This!

**Comment by remcoros** [comment]
done, I also configured appveyor build with release artifacts and added the build status badge to the readme.

**Comment by MrChriZ** [comment]
Awesome Thanks!

**Comment by drewnoakes** [comment]
Would be good to link to the artifacts from the readme. Currently it says you have to build it yourself.

I assume this is the link:

https://ci.appveyor.com/project/remcoros/duplicateextensionfinder/build/artifacts
